Add IPubFailure event handler
zopefoundation/Products.SiteErrorLog pull request #8
Opened 2018-05-18 12:45 UTC by rbu

@icemac We talked about this earlier during the sprint. Do you think this code makes sense?

2018-05-23 15:11 UTC, icemac requested changes
Thank you for working on this PR. It mostly LGTM. Only the registration of the event handler should be moved to ZCML. This might require to change the test so it loads the ZCML. (Ask me for pointers how to do this if needed.)

Additionally a change log entry would be nice.

2018-05-23 15:11 UTC, icemac commented on src/Products/SiteErrorLog/SiteErrorLog.py
> +provideHandler(_handle_wsgi_publisher_failure)
Registering the handler should be done via ZCML in `configure.zcml` so it is registered in the correct registry.

See https://github.com/zopefoundation/zope.catalog/blob/ccbd0f444a0dd69d4fa244741215f43e9ef46648/src/zope/catalog/subscribers.zcml as an example.

2018-05-23 15:11 UTC, icemac commented on src/Products/SiteErrorLog/SiteErrorLog.py
> +    published = event.request.get('PUBLISHED')
A docstring would be nice.

2018-05-29 10:03 UTC, rbu commented
Fixed the points you raised, closing in favor of PR #9

2018-05-29 10:03 UTC, closed without merging